### ISSUE TITLE
[Suggestion] setup.py discord.py changes

### ISSUE THREAD

**Issue by xFGhoul** [discordsuperutils/discord-super-utils#33]
First of all, thanks for making an amazing library but the one caviat I have is this requires `discord.py` to be installed and now I'm suggesting either:

1.
remove `discord.py` completely from `setup.py`

2.
seperate into popular forks so it's like
`python -m pip install discordSuperUtils[default]` (Installs with discord.py)
`python -m pip install discordSuperUtils[pycord]` (installs pycord)

**Comment by adam757521** [comment]
Hey, thank you for liking my library, but having separate forks that use 2 different libraries would result in a lot of code changes as most of the features in discord.py are very different in pycord.
But, there are some forks of discordSuperUtils, such as pycordSuperUtils or disnakeSuperUtils, that supports these libraries.
Please take a look at them, they are not perfect, but they might work.
