### ISSUE TITLE
bot left the voice chat when is playing song. 

### ISSUE THREAD

**Issue by PATATAGAME554** [discordsuperutils/discord-super-utils#37]
the bot left the voice chat when is playing song, i don't know why do this, some help?

**Comment by Heapy1337** [comment]
Is it always happening at the end of the songs?

**Comment by PATATAGAME554** [comment]
> 

no, at 30 seconds after playing

**Comment by Heapy1337** [comment]
Then do " inactivity_timeout​ = None"

It should look like this :
MusicManager = discordSuperUtils.MusicManager(<add it here>)

**Comment by PATATAGAME554** [comment]
> Then add " inactivity_timeout​ = None" to MusicManager
> 
> It should look like this : MusicManager = discordSuperUtils.MusicManager(add it here)

thanks!

**Comment by PATATAGAME554** [comment]
> Then add " inactivity_timeout​ = None" to MusicManager
> 
> It should look like this : MusicManager = discordSuperUtils.MusicManager(add it here)

don't work, error: missing 1 required positional argument: "bot"

**Comment by Heapy1337** [comment]
> > Then add " inactivity_timeout​ = None" to MusicManager
> > It should look like this : MusicManager = discordSuperUtils.MusicManager(add it here)
> 
> don't work, error: missing 1 required positional argument: "bot"

Show me your code

**Comment by PATATAGAME554** [comment]
> > > Then add " inactivity_timeout​ = None" to MusicManager
> > > It should look like this : MusicManager = discordSuperUtils.MusicManager(add it here)
> > 
> > 
> > don't work, error: missing 1 required positional argument: "bot"
> 
> Show me your code




client = commands.Bot(command_prefix = '!')
MusicManager = MusicManager(client, client_id=client_id, client_secret=client_secret, spotify_support=True)
slash = SlashCommand(client, sync_commands=True)
intents = discord.Intents.default()  
intents.members = True
MusicManager = discordSuperUtils.MusicManager(inactivity_timeout = None)

**Comment by Heapy1337** [comment]
You have two MusicManagers, combine them into one

```
client = commands.Bot(command_prefix = '!')
MusicManager = MusicManager(client, client_id=client_id, client_secret=client_secret, spotify_support=True, inactivity_timeout = None)
slash = SlashCommand(client, sync_commands=True)
intents = discord.Intents.default()
intents.members = True
```

**Comment by PATATAGAME554** [comment]
> You have two MusicManagers, combine them into one
> 
> ```
> client = commands.Bot(command_prefix = '!')
> MusicManager = MusicManager(client, client_id=client_id, client_secret=client_secret, spotify_support=True, inactivity_timeout = None)
> slash = SlashCommand(client, sync_commands=True)
> intents = discord.Intents.default()
> intents.members = True
> ```

okkk thanks
