### ISSUE TITLE
on_play is never dispatched

### ISSUE THREAD

**Issue by xFGhoul** [discordsuperutils/discord-super-utils#40]
title is the issue, no matter what I do `on_play` is never dispatched, now I do have a subclassed version of `commands.Cog` but that shouldn't matter...right? not sure.

**Comment by xFGhoul** [comment]
Update, no events are fired, `on_queue_end`, `on_activity_disconnect`, all don't dispatch

**Comment by adam757521** [comment]
You probably used the wrong decorator on the event callback.
Join the discord incase you need more help.
